analytics.onpremise.enable=true
onpremise.email="mukesh.jain@crmit.com"
onpremise.password="izS+2DyR6/buFB1Hsmq8CQ\=\="
analytics.onpremise.organization="{\\"accountId\\"\:1425610,\\"id\\"\:1700240,\\"name\\"\:\\"My Organization_01\\",\\"role\\"\:\\"OWNER\\",\\"samlSSO\\"\:false,\\"kreLicense\\"\:false,\\"strictDomain\\"\:false}"
analytics.onpremise.server="https\://testops.katalon.io"
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 2064149,\\n  \\"name\\"\: \\"KATALON_DEMO_TO_DELIVERY_TEAM\\",\\n  \\"teamId\\"\: 2044570,\\n  \\"organizationId\\"\: 1700240,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 2044570\\n}"
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=true
