<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Employee_Login</description>
   <name>Employee_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d0e79e58-fcb6-4306-bd9d-ac7ed02f4cad</testSuiteGuid>
   <testCaseLink>
      <guid>2523a887-f468-403a-af6c-ac0ae949f36f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Credential/Employee_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53b8592e-762f-4822-9c57-a42d0ff962a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dea1551-4298-4f6f-aeca-3cc3c094662e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89c46c6f-6750-4ad2-8d71-74a43e8d132e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
