<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Approval_Status</name>
   <tag></tag>
   <elementGuidId>694638d8-fc07-4180-ab9f-c5cfdcda78bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span//span[contains(text(),&quot;Rejected&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
