<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dynamic_Leave_Type</name>
   <tag></tag>
   <elementGuidId>95a1389f-8fd4-4286-8b1c-8e9589756f49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Paternity LeaveTotal: 50Remaining: 50' or . = 'Paternity LeaveTotal: 50Remaining: 50')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-type = 'Paternity' and (text() = 'Paternity LeaveTotal: 50Remaining: 50' or . = 'Paternity LeaveTotal: 50Remaining: 50')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Paternity LeaveTotal: 50Remaining: 50$/ >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dbcb95b5-c934-45b3-b7aa-e4b4f2f20860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>Paternity</value>
      <webElementGuid>5797db39-1e7f-4a22-a2da-401b20287272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leave__tile</value>
      <webElementGuid>2f59f5f5-ff2d-4fea-8fd7-7b41fd8822a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paternity LeaveTotal: 50Remaining: 50</value>
      <webElementGuid>fb184af6-ff09-453f-a7bc-71ae5c67f9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;slds-no-wcag&quot;]/body[@class=&quot;null comm-page-custom-applyleave&quot;]/div[@class=&quot;themeLayoutStarterWrapper isHeroUnderHeader-false isHeaderPinned-false siteforceThemeLayoutStarter&quot;]/div[@class=&quot;body isPageWidthFixed-true&quot;]/div[@class=&quot;siteforceDynamicLayout siteforceContentArea&quot;]/div[1]/div[@class=&quot;ui-widget&quot;]/div[@class=&quot;cb-section forceCommunitySection&quot;]/div[@class=&quot;cb-section_row slds-grid slds-wrap slds-large-nowrap&quot;]/div[@class=&quot;cb-section_column slds-size_12-of-12 slds-max-medium-size_12-of-12&quot;]/div[1]/div[@class=&quot;ui-widget&quot;]/c-apply-leave[1]/div[@class=&quot;main__container&quot;]/article[@class=&quot;slds-card&quot;]/div[@class=&quot;slds-card__body slds-card__body_inner&quot;]/div[@class=&quot;container&quot;]/c-leave-cards[1]/div[@class=&quot;leave__stats&quot;]/div[@class=&quot;leave__tile&quot;]</value>
      <webElementGuid>2ebee7da-363d-4982-b81c-5fc36b6bf483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Paternity LeaveTotal: 50Remaining: 50' or . = 'Paternity LeaveTotal: 50Remaining: 50')]</value>
      <webElementGuid>46b06ee0-1beb-42bf-92bc-e31cec2da0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]</value>
      <webElementGuid>70b9ad30-5eb3-4a6b-b7fd-95384df52678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
